[project]
name = "profiling-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.1.2",
    "invoke>=2.2.0",
]
